Обратная сторона реальности
Jahonta/1215637-six-cities-9 pull request #1
Opened 2022-02-22 11:12 UTC by Jahonta

https://up.htmlacademy.ru/react/9/tasks/5

2022-02-22 17:34 UTC, Finnko requested changes

2022-02-22 17:34 UTC, Finnko commented on project/src/components/navigation/navigation.tsx
> +          <li className="header__nav-item">
Норм вариант, но не хотелось бы дублировать разметку. У нас от условия вывод только этого последнего пункта и заменить спан выше. Также с бека нам будет приходить аватар, который можно будет поставить для дива 'user__avatar-wrapper'

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +  const capitalizedType = capitalize(type);
Лайк

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +  extraClass: string;
обычно пропс с внешним классом называют className, но учитывая нашу разметку непростую extraClass подойдет больше

2022-02-22 17:34 UTC, Finnko commented on project/src/components/app/app.tsx
> +          path={AppRoute.Offer}
Это лично мой пункт но я предпочитаю явно видеть какой параметр передается. Плюс сразу понятно что путь динамический

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +  const offerPageUrl = AppRoute.OfferBase + id;
Мне кажется можно не выносить и записать прямо в линк так. Либо ты можешь собирать путь через функцию generatePath 
```suggestion
  ={`${AppRoute.OfferBase}/${id}`};
```

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +  const ratingWidth = `${Math.round(rating) * 20}%`;
Будет понятнее если ты явно покажешь как получилось 20

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +      onMouseEnter={() => onMouseEnter?.(id)}
👍 за optional chaining для функций

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +      onMouseLeave={onMouseLeave}
В целом можно было использовать 1 функцию просто на наведении кидать id, когда убираем - null

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +      )}
Я бы вынес отдельно в компонент беджика

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +              isFavorite && 'place-card__bookmark-button--active'
Желательно использовать [classnames](https://www.npmjs.com/package/classnames) Это дефолт для стилей если у нас не css in js

2022-02-22 17:34 UTC, Finnko commented on project/src/components/offer-card/offer-card.tsx
> +          <button
Стоит вынести отдельно в компонент Bookmark. Потом на ней будет доп логика

2022-02-22 17:34 UTC, Finnko commented on project/src/components/reviews-form/reviews-form.tsx
> +  ));
Я бы вынес это в отдельный компонент Rating

2022-02-22 17:34 UTC, Finnko commented on project/src/components/reviews-form/reviews-form.tsx
> +function ReviewsForm() {
Это форма 1 коммента
```suggestion
function ReviewForm() {
```

2022-02-22 17:34 UTC, Finnko commented on project/src/components/reviews-form/reviews-form.tsx
> +  const [review, setReview] = useState<string>('');
Давай объединим в один стейт, так как форма 1 и сделаем один [обработчик](https://ru.reactjs.org/docs/forms.html#handling-multiple-inputs) handleChange для формы. Так как поля могут добавляться и не хотелось бы заводить под каждый стейт и хендлер. Ну и для тренировки)

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/favorites-page/favorites-page.tsx
> +  const result: OffersToCities = {};
Давай уберем это объявление объекта и сделаем замением forEach на reducе. В принципе вообще можно было бы сделать все 1 проход без фильтра, но с фильтром нагляднее кмк

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/favorites-page/favorites-page.tsx
> +  const isEmpty = cities.length === 0;
Можно так
```suggestion
  const isEmpty = Boolean(cities.length);
  const isEmpty = !!cities.length;
```

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/favorites-page/favorites-page.tsx
> +            </section>
Давай вынесем отдельно в FavoritesEmpty. Будет нагляднее, а отдельно можно не выносить просто выше описать

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/favorites-page/favorites-page.tsx
> +                        <Link className="locations__item-link" to="#">
Конкретно здесь Link не нужен у нас не будет никакого взаимодействия с локейшнс

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/not-found-page/not-found-page.module.css
> +.NotFound {
А почему с большой?)
```suggestion
.notFound {
```

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/not-found-page/not-found-page.tsx
> +import classes from './not-found-page.module.css';
Лучше использовать общепринятое styles 
```suggestion
import styles from './not-found-page.module.css';
```

2022-02-22 17:34 UTC, Finnko commented on project/src/pages/offer-page/offer-page.tsx
> +  if (!offer) {
Допустим айдишника нет и find не найдет нам элемент. Но это условие включает в себя верхнее

2022-02-23 08:54 UTC, Jahonta commented on project/src/components/navigation/navigation.tsx
> +          <li className="header__nav-item">
Наверное, я пока не на том этапе понимания проекта. Пока мне кажется, что все пункты меняются, поэтому я полностью изменяю навигацию...
Давай я пока оставим всё как есть в качестве временного решения. А когда дойду до авторизации и работы с бэком, то вернусь к этому компоненту и подумаю ещё раз.

2022-02-23 09:05 UTC, Jahonta commented on project/src/components/reviews-form/reviews-form.tsx
> +  const [review, setReview] = useState<string>('');
А может, не надо?
Я тут прям очень сильно согласна с Сашей Сушко: если можно разделить состояние на несколько кусков, то лучше разделить. Так удобнее же. Тем более что рейтинг теперь в отдельном компоненте живёт.

Мы знаем, что новые поля не появятся (и вообще - преждевременная оптимизация ). А один обработчик вешать или два - экономия минимальная.

2022-02-23 09:05 UTC, Jahonta commented on project/src/pages/favorites-page/favorites-page.tsx
> +  const isEmpty = cities.length === 0;
Можно. Но мой вариант кажется чуть более наглядным. Я б оставила...

2022-02-23 09:07 UTC, Jahonta commented on project/src/pages/favorites-page/favorites-page.tsx
> +                        <Link className="locations__item-link" to="#">
Хм... а если всё-таки добавить взаимодействие? Например, перенаправление на главную с фильтрацией по этому самому городу?..
Не по ТЗ, но и пусть. Зато потренируюсь работать с searchParams и просто улучшу UX.

Можно?

2022-02-23 09:36 UTC, merged